### ISSUE TITLE
Project 2 Feedback

### ISSUE THREAD

**Issue by Avizacherman** [sfrieson/RestPos#1]
Steven,

Your backend is great overall. You've written nice complete and concise code and seem to have a firm grasp on Rails and Rspec.  Love that you used ActiveRecord Callbacks like we had spoken about. Great way to automate some code. 

I'm getting an error when I try to go to your deployment on Heroku so I can't actually give feedback on it at the moment or mark the project as complete until we get that fixed. Let's hook up and see what's going on. It's probably something minor.

-Avi

**Comment by Avizacherman** [comment]
Thank you for the quick fix! Website looks great. Love all the functionality you threw in there. 

Score: 2.5 out of 3

**Comment by sfrieson** [comment]
Thanks Avi!

-Steven
